export const hexColorData = {
    '#A52A2A': { group: 'Browns', name: 'Auburn' },
    '#80461B': { group: 'Browns', name: 'Russet' },
    '#704214': { group: 'Browns', name: 'Sepia' },
    '#954535': { group: 'Browns', name: 'Chestnut' },
    '#A0522D': { group: 'Browns', name: 'Sienna' },
    '#8B4513': { group: 'Browns', name: 'Wood' },
    '#B06500': { group: 'Browns', name: 'Ginger' },
    '#B87333': { group: 'Browns', name: 'Copper' },
    '#C19A6B': { group: 'Browns', name: 'Maple' },
    '#C2B280': { group: 'Browns', name: 'Ecru' },
    '#DAA520': { group: 'Browns', name: 'Hazel' },
    '#D2B48C': { group: 'Browns', name: 'Light Brown' },
    '#CC7722': { group: 'Browns', name: 'Ochre' },
    '#8D4E2B': { group: 'Browns', name: 'Mocha' },
    '#FFDB58': { group: 'Browns', name: 'Mustard' },
    '#FFDDC1': { group: 'Browns', name: 'Nude' },
    '#967117': { group: 'Browns', name: 'Olive Skin' },
    '#EFDECD': { group: 'Browns', name: 'Almond' },
    '#635147': { group: 'Browns', name: 'Umber' },
    '#AA8D6F': { group: 'Browns', name: 'Sandal' },
    '#8A3324': { group: 'Browns', name: 'Oak' },
    '#0F52BA': { group: 'Blues', name: 'Sapphire' },
    '#007FFF': { group: 'Blues', name: 'Azul' },
    '#2A52BE': { group: 'Blues', name: 'Cerulean' },
    '#00008B': { group: 'Blues', name: 'Dark Blue' },
    '#87CEEB': { group: 'Blues', name: 'Sky Blue' },
    '#0047AB': { group: 'Blues', name: 'Cobalt' },
    '#87CEFF': { group: 'Blues', name: 'Sky' },
    '#0000FF': { group: 'Blues', name: 'Blue' },
    '#89CFF0': { group: 'Blues', name: 'Baby Blue' },
    '#ADD8E6': { group: 'Blues', name: 'Ice Blue' },
    '#607C8E': { group: 'Blues', name: 'Blue Grey' },
    '#120A8F': { group: 'Blues', name: 'Ultramarine' },
    '#4169E1': { group: 'Blues', name: 'Royal Blue' },
    '#000080': { group: 'Blues', name: 'Ocean Blue' },
    '#6082B6': { group: 'Blues', name: 'Glaucous' },
    '#708090': { group: 'Blues', name: 'Slate' },
    '#B0E0E6': { group: 'Blues', name: 'Powder Blue' },
    '#87CEFA': { group: 'Blues', name: 'Water' },
    '#4682B4': { group: 'Blues', name: 'Steel Blue' },
    '#7FFF00': { group: 'Yellows', name: 'Chartreuse' },
    '#FFF700': { group: 'Yellows', name: 'Lemon' },
    '#F0DC82': { group: 'Yellows', name: 'Buff' },
    '#FBEC5D': { group: 'Yellows', name: 'Maize' },
    '#F3E5AB': { group: 'Yellows', name: 'Vanilla' },
    '#FDE91A': { group: 'Yellows', name: 'Happy' },
    '#FFFE71': { group: 'Yellows', name: 'Pastel Yellow' },
    '#D4AF37': { group: 'Yellows', name: 'Gold' },
    '#FFE302': { group: 'Yellows', name: 'Vivid Yellow' },
    '#FFF44F': { group: 'Yellows', name: 'Lemon Yellow' },
    '#FFBF00': { group: 'Yellows', name: 'Amber' },
    '#FFDF00': { group: 'Yellows', name: 'Golden Yellow' },
    '#FFFF99': { group: 'Yellows', name: 'Canary Yellow' },
    '#FFFF00': { group: 'Yellows', name: 'Yellow' },
    '#9ACD32': { group: 'Yellows', name: 'Yellow Green' },
    '#3EB489': { group: 'Greens', name: 'Mint' },
    '#98FB98': { group: 'Greens', name: 'Mint Green' },
    '#4B5320': { group: 'Greens', name: 'Army Green' },
    '#1D4F2B': { group: 'Greens', name: 'Evergreen' },
    '#006A4E': { group: 'Greens', name: 'Bottle Green' },
    '#32CD32': { group: 'Greens', name: 'Lime Green' },
    '#50C878': { group: 'Greens', name: 'Emerald' },
    '#2E8B57': { group: 'Greens', name: 'Sea Green' },
    '#61C0BF': { group: 'Greens', name: 'Matcha' },
    '#8DB600': { group: 'Greens', name: 'Apple Green' },
    '#90EE90': { group: 'Greens', name: 'Light Green' },
    '#4CBB17': { group: 'Greens', name: 'Kelly Green' },
    '#C3B091': { group: 'Greens', name: 'Khaki' },
    '#556B2F': { group: 'Greens', name: 'Olive Green' },
    '#008000': { group: 'Greens', name: 'Green' },
    '#008A74': { group: 'Greens', name: 'Emerald Green' },
    '#355E3B': { group: 'Greens', name: 'Hunter Green' },
    '#228B22': { group: 'Greens', name: 'Forest Green' },
    '#808000': { group: 'Greens', name: 'Olive' },
    '#B5A642': { group: 'Greens', name: 'Brass' },
    '#87AE73': { group: 'Greens', name: 'Sage' },
    '#93C572': { group: 'Greens', name: 'Pistachio' },
    '#2D572C': { group: 'Greens', name: 'Esmeralda' },
    '#008080': { group: 'Greens', name: 'Teal Green' },
    '#E2725B': { group: 'Oranges', name: 'Terracotta' },
    '#CC5500': { group: 'Oranges', name: 'Burnt Orange' },
    '#CD7F32': { group: 'Oranges', name: 'Bronze' },
    '#E5AA70': { group: 'Oranges', name: 'Fawn' },
    '#EAA221': { group: 'Oranges', name: 'Marigold' },
    '#F4C430': { group: 'Oranges', name: 'Saffron' },
    '#FFD700': { group: 'Oranges', name: 'Honey' },
    '#FFA07A': { group: 'Oranges', name: 'Light Orange' },
    '#FBCEB1': { group: 'Oranges', name: 'Apricot' },
    '#FF4500': { group: 'Oranges', name: 'Orange Red' },
    '#FF7F50': { group: 'Oranges', name: 'Coral' },
    '#FF8C00': { group: 'Oranges', name: 'Dark Orange' },
    '#F28500': { group: 'Oranges', name: 'Tangerine' },
    '#FFA500': { group: 'Oranges', name: 'Orange' },
    '#FF8D42': { group: 'Oranges', name: 'Mango' },
    '#FFA54F': { group: 'Oranges', name: 'Topaz' },
    '#FFDAB9': { group: 'Oranges', name: 'Peach' },
    '#E97451': { group: 'Oranges', name: 'Burnt Sienna' },
    '#C71585': { group: 'Pinks', name: 'Mulberry' },
    '#CC8899': { group: 'Pinks', name: 'Puce' },
    '#DA70D6': { group: 'Pinks', name: 'Orchid' },
    '#8E4585': { group: 'Pinks', name: 'Plum' },
    '#FF91A4': { group: 'Pinks', name: 'Candy' },
    '#E0AC69': { group: 'Pinks', name: 'Skin' },
    '#E0115F': { group: 'Pinks', name: 'Ruby' },
    '#FD3F92': { group: 'Pinks', name: 'Fuchsia' },
    '#FFB6C2': { group: 'Pinks', name: 'Pastel Pink' },
    '#F4C2C2': { group: 'Pinks', name: 'Baby Pink' },
    '#DE5D83': { group: 'Pinks', name: 'Blush' },
    '#FF007F': { group: 'Pinks', name: 'Rose' },
    '#FA8072': { group: 'Pinks', name: 'Salmon' },
    '#FE9DA1': { group: 'Pinks', name: 'Rosa' },
    '#FF00FF': { group: 'Pinks', name: 'Magenta' },
    '#FF6FFF': { group: 'Pinks', name: 'Blush Pink' },
    '#FF66CC': { group: 'Pinks', name: 'Rose Pink' },
    '#FF69B4': { group: 'Pinks', name: 'Hot Pink' },
    '#FFB6C1': { group: 'Pinks', name: 'Light Pink' },
    '#FFC0CB': { group: 'Pinks', name: 'Pink' },
    '#E75480': { group: 'Pinks', name: 'Dusty Pink' },
    '#E52B50': { group: 'Pinks', name: 'Amaranth' },
    '#A52A2B': { group: 'Pinks', name: 'Rouge' },
    '#FFDDCD': { group: 'Pinks', name: 'Nude Pink' },
    '#9DBEAA': { group: 'Greys', name: 'Sage Green' },
    '#536878': { group: 'Greys', name: 'Gunmetal' },
    '#5A6E8C': { group: 'Greys', name: 'Dusty Blue' },
    '#8A496B': { group: 'Greys', name: 'Purpura' },
    '#8C8E94': { group: 'Greys', name: 'Pewter' },
    '#BBB7AE': { group: 'Greys', name: 'Evergreen Fog' },
    '#738678': { group: 'Greys', name: 'Xanadu' },
    '#808080': { group: 'Greys', name: 'Grey' },
    '#333333': { group: 'Greys', name: 'Dark Grey' },
    '#483C32': { group: 'Greys', name: 'Taupe' },
    '#8C7151': { group: 'Greys', name: 'Clay' },
    '#B8B3A7': { group: 'Greys', name: 'Greige' },
    '#B0B7C6': { group: 'Greys', name: 'Mercury' },
    '#C0C0C0': { group: 'Greys', name: 'Silver' },
    '#AEC6CF': { group: 'Greys', name: 'Pastel Blue' },
    '#E5E4E2': { group: 'Greys', name: 'Platinum' },
    '#756F6D': { group: 'Greys', name: 'Dorado' },
    '#C3C3BD': { group: 'Greys', name: 'Titanium' },
    '#D3D3D3': { group: 'Greys', name: 'Light Grey' },
    '#FFFFFF': { group: 'Whites', name: 'White' },
    '#F5F5F5': { group: 'Whites', name: 'Dirty White' },
    '#F0FFFF': { group: 'Whites', name: 'Azure' },
    '#E4D8B9': { group: 'Whites', name: 'Bone' },
    '#FAEBD7': { group: 'Whites', name: 'Alabaster' },
    '#FFFFFE': { group: 'Whites', name: 'Clear' },
    '#F4F2E5': { group: 'Whites', name: 'Pearl' },
    '#F5F5DC': { group: 'Whites', name: 'Beige' },
    '#FFFFF0': { group: 'Whites', name: 'Off White' },
    '#F0F0F0': { group: 'Whites', name: 'Moon' },
    '#F7E7CE': { group: 'Whites', name: 'Champagne' },
    '#FFF8DC': { group: 'Whites', name: 'Pearl White' },
    '#FAF0E6': { group: 'Whites', name: 'Linen' },
    '#FFFAF0': { group: 'Whites', name: 'White Cream' },
    '#FAD6A5': { group: 'Whites', name: 'Pale' },
    '#FFFDD0': { group: 'Whites', name: 'Cream' },
    '#FFFFF1': { group: 'Whites', name: 'Ivory' },
    '#F0F8FF': { group: 'Whites', name: 'Alice Blue' },
    '#FFDAB8': { group: 'Whites', name: 'Light Peach' },
    '#000000': { group: 'Blacks', name: 'Black' },
    '#001F3F': { group: 'Blacks', name: 'Navy Blue' },
    '#36454F': { group: 'Blacks', name: 'Charcoal' },
    '#46174C': { group: 'Blacks', name: 'Aubergine' },
    '#222222': { group: 'Blacks', name: 'Ebony' },
    '#003366': { group: 'Blacks', name: 'Midnight Blue' },
    '#006400': { group: 'Blacks', name: 'Dark Green' },
    '#424242': { group: 'Blacks', name: 'Graphite' },
    '#000081': { group: 'Blacks', name: 'Navy' },
    '#300A24': { group: 'Blacks', name: 'Dark Purple' },
    '#353839': { group: 'Blacks', name: 'Onyx' },
    '#311B92': { group: 'Blacks', name: 'Eggplant' },
    '#673147': { group: 'Blacks', name: 'Deep Purple' },
    '#000741': { group: 'Blacks', name: 'Stratos' },
    '#001F3G': { group: 'Blacks', name: 'Deep Blue' },
    '#7851A9': { group: 'Purples', name: 'Royal Purple' },
    '#4B0082': { group: 'Purples', name: 'Indigo' },
    '#8A2BE2': { group: 'Purples', name: 'Blue Violet' },
    '#5A4FCF': { group: 'Purples', name: 'Iris' },
    '#4E387E': { group: 'Purples', name: 'Purple Blue' },
    '#EE82EE': { group: 'Purples', name: 'Violet' },
    '#9370DB': { group: 'Purples', name: 'Blue Purple' },
    '#9966CC': { group: 'Purples', name: 'Amethyst' },
    '#8B3A3A': { group: 'Purples', name: 'Neon Purple' },
    '#800080': { group: 'Purples', name: 'Purple' },
    '#996666': { group: 'Purples', name: 'Heather' },
    '#DCD0FF': { group: 'Purples', name: 'Light Purple' },
    '#9068BE': { group: 'Purples', name: 'Autumn Wisteria' },
    '#C5D0E6': { group: 'Purples', name: 'Periwinkle' },
    '#51484F': { group: 'Purples', name: 'Quartz' },
    '#C8A2C8': { group: 'Purples', name: 'Lilac' },
    '#E0B0FF': { group: 'Purples', name: 'Mauve' },
    '#E6E6FA': { group: 'Purples', name: 'Lavender' },
    '#00FFFF': { group: 'Teals', name: 'Cyan' },
    '#008081': { group: 'Teals', name: 'Azul Turquesa' },
    '#0ABAB5': { group: 'Teals', name: 'Tiffany Blue' },
    '#7DF9FF': { group: 'Teals', name: 'Electric Blue' },
    '#7FFFD4': { group: 'Teals', name: 'Aquamarine' },
    '#4B0083': { group: 'Teals', name: 'Indicolite' },
    '#40E0D0': { group: 'Teals', name: 'Turquoise' },
    '#00FFFE': { group: 'Teals', name: 'Aqua' },
    '#00CED1': { group: 'Teals', name: 'Aqua Blue' },
    '#0666D0': { group: 'Teals', name: 'Blue Green' },
    '#40826D': { group: 'Teals', name: 'Viridian' },
    '#008082': { group: 'Teals', name: 'Teal' },
    '#367588': { group: 'Teals', name: 'Teal Blue' },
    '#ADD8E5': { group: 'Teals', name: 'Blue Light' },
    '#AFEEEE': { group: 'Teals', name: 'Uranus' },
    '#B2FFFF': { group: 'Teals', name: 'Celeste' },
    '#ACE1AF': { group: 'Teals', name: 'Celadon' },
    '#005F6A': { group: 'Teals', name: 'Petrol' },
    };
    